<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>BTitles</AssemblyName>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="localization\es-ES.hjson" />
    <None Remove="localization\fr-FR.hjson" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\Textures\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="tModLoader">
      <HintPath>"C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.dll"</HintPath>
    </Reference>
    <Reference Include="TerrariaHooks">
      <HintPath>"C:\Program Files (x86)\Steam\steamapps\common\tModLoader\Libraries\TerrariaHooks\0.0.0.0\TerrariaHooks.dll"</HintPath>
    </Reference>
  </ItemGroup>
</Project>